# -*- mode: python -*-
###############################################################
# Top level SConscript for the fluxus RACKET modules
#
# Sets up common stuff, and calls each module SConscript 

import os 
Import("env", "CollectsInstall", "DataInstall", "MZDYN",
		"static_modules", "static_ode", "Prefix")

# run mzscheme to get (path->string (system-library-subpath))
file = os.popen("mzscheme -em \"(begin (display (path->string (system-library-subpath)))(exit))\"")
archpath = file.read()
file.close()

BinaryModulesLocation = CollectsInstall + "/compiled/native/"+archpath

if env['PLATFORM'] == 'win32':
	SConscript(dirs = ["fluxus-engine", 
				"fluxus-openal",
				"scheme",
				"material"], 
				exports = ["env", "CollectsInstall", "DataInstall", "BinaryModulesLocation",
					"MZDYN", "static_modules", "static_ode", "Prefix"])
else:
	SConscript(dirs = ["fluxus-engine", 
				"fluxus-audio", 
				"fluxus-osc", 
				"fluxus-midi", 
				"fluxus-openal", 
				"scheme",
				"material"], 
				exports = ["env", "CollectsInstall", "DataInstall", "BinaryModulesLocation",
					"MZDYN", "static_modules", "static_ode", "Prefix"])

env.Install(CollectsInstall, "../docs/helpmap.scm")

