Target       = "libfluxus.so"
Install   	 = "/usr/local/lib"
IncInstall	 = "/usr/local/include/fluxus"
LibPaths     = Split("/usr/local/lib /usr/X11R6/lib")
IncludePaths = Split("/usr/local/include")
	  
Libs = Split("png glut GL GLU z m Xi Xmu Xext X11")

Source = Split("src/GraphicsUtils.cpp \
				src/Lifeforms.cpp \
				src/PNGLoader.cpp \
				src/PolyPrimitive.cpp \
				src/TextPrimitive.cpp \
				src/CompiledPrimitive.cpp \
				src/LinePrimitive.cpp \
				src/Primitive.cpp \
				src/Light.cpp \
				src/Renderer.cpp \
				src/SceneGraph.cpp \
				src/State.cpp \
				src/TexturePainter.cpp \
				src/Tree.cpp \
				src/dada.cpp")	
								
Headers = Split("src/GraphicsUtils.h \
				src/Lifeforms.h \
				src/PNGLoader.h \
				src/PolyPrimitive.h \
				src/TextPrimitive.h \
				src/CompiledPrimitive.h \
				src/LinePrimitive.h \
				src/Primitive.h \
				src/Light.h \
				src/Renderer.h \
				src/SceneGraph.h \
				src/State.h \
				src/TexturePainter.h \
				src/Tree.h \
				src/dada.h")
		
env = Environment(CCFLAGS = '-pipe -Wall -O3 -ggdb -ffast-math -Wno-unused -fPIC')
env.SharedLibrary(source = Source, target = Target, LIBS=Libs, LIBPATH=LibPaths, CPPPATH=IncludePaths)

env.Install(IncInstall, Headers)
env.Alias('install', IncInstall)

env.Install(Install, Target)
env.Alias('install', Install)
