Target       = "libfluxphysics.so"
Install   	 = "/usr/local/lib"
IncInstall	 = "/usr/local/include/fluxus"
LibPaths     = Split("/usr/local/lib /usr/X11R6/lib")
IncludePaths = Split("/usr/local/include")
	  
Libs = Split("fluxus ode")

Source = Split("src/Physics.cpp")				
Headers = Split("src/Physics.h")
		
env = Environment(CCFLAGS = '-pipe -Wall -O3 -ggdb -ffast-math -Wno-unused -fPIC')
env.SharedLibrary(source = Source, target = Target, LIBS=Libs, LIBPATH=LibPaths, CPPPATH=IncludePaths)

env.Install(IncInstall, Headers)
env.Alias('install', IncInstall)

env.Install(Install, Target)
env.Alias('install', Install)
