#-*- mode: python -*-
###############################################################
# Top level SConscript for the fluxus additional modules
#
# Sets up common stuff, and calls each module SConscript 

import os 
Import("env", "CollectsInstall", "DataInstall", "MZDYN", "static_modules", "racket_framework")

# run mzscheme to get (path->string (system-library-subpath))
file = os.popen("racket -em \"(begin (display (path->string (system-library-subpath)))(exit))\"")
archpath = file.read()
file.close()

BinaryModulesLocation = CollectsInstall + "/compiled/native/"+archpath

SConscript(dirs = env.Split("video artkp"),
		exports = ["env", "CollectsInstall", "DataInstall", "BinaryModulesLocation",
			"MZDYN", "static_modules", "racket_framework"])

