(define speed 10)
(define rotsp 2)

(define (spawn)
	(push)
		(opacity 1)
		(translate (vector (* (flxrnd) 1) 5 (* (flxrnd) 1)))
		(scale (vector (*(gh 4)5) 0.1 (*(gh 9)5)))
		(shinyness 1)
		(specular (vector 0 0 0))
		(colour (vector (gh 4) (gh 6) (gh 8)))
		(let ((ob (build_cube)))	
			(active_box ob)
			(kick ob (vector (*(gh 5)speed) (*(gh 7)speed) (*(gh 9)speed) ))
			(twist ob (vector (* (- (gh 13) 0.5) rotsp) 
							  (* (- (gh 14) 0.5) rotsp) 
							  (* (- (gh 15) 0.5) rotsp) )))
	(pop))

(ground_plane (vector 0 1 0) 0)
(set_max_physical 500)
(blur 0)

(define (run_loop)	
	 (spawn))
	;(if (> (gh 10) 0.2) (spawn)))

(line_width 5)
(clear)
(ground_plane (vector 0 1 0) 0)	
(engine_callback "(run_loop)")

(show_axis 0)
(clear_colour (vector 0 0 0))
(blur 1)