(define feet 0)
(define legs 0)
(define torso 0)
(define head 0)
(define arm1 0)
(define arm2 0)

(define (build)
	(push)
	(opacity 0.1)
	(colour (vector 1 1 1))
	(set! feet (build_cube))
	(parent feet)
	(set! legs (build_cube))
	(parent legs)
	(set! torso (build_cube))
	(parent torso)
	(set! arm1 (build_cube))
	(set! arm2 (build_cube))
	(texture (load_texture "smiley.png"))
	(set! head (build_cube))
	(pop))

(define (animate)
	(grab feet)
	(identity)
	(translate (vector 1 0.01 0))
	(rotate (vector 0 (* (-(gh 1) 0.5) 45) 270))
	(ungrab)
	
	(grab legs)
	(identity)
	(translate (vector 1 0.01 0))
	(rotate (vector 0 (* (-(gh 3) 0.5) 45) 0))
	(scale (vector 0.7 0.7 0.7))
	(ungrab)	

	(grab torso)
	(identity)
	(translate (vector 1.2 0.01 0))
	(rotate (vector (* (-(gh 5) 0.5) 45) (* (-(gh 2) 0.5) 45) 0))
	(scale (vector 1.2 1.2 1.2))	
	(ungrab)	

	(grab head)
	(identity)
	(translate (vector 1 0.01 0))
	(rotate (vector 0 (* (-(gh 7) 0.5) 45) 0))
	(scale (vector 0.5 0.5 0.5))
	(ungrab)
	
	(grab arm1)
	(identity)
	(translate (vector 0 -1 0))
	(rotate (vector 0 0 (* (-(gh 9) 0.5) 90)))
	(scale (vector 1 0.3 0.3))
	(ungrab)

	(grab arm2)
	(identity)
	(translate (vector 0 1 0))
	(rotate (vector 0 0 (* (-(gh 2) -0.5) 90)))
	(scale (vector 1 0.3 0.3))
	(ungrab))

(clear)
(build)
(blur 0.1)
(clear_colour (vector 1 1 1))
(engine_callback "(animate)")