(define speed 10)
(define rotsp 2)

(define (spawn)
	(push)
		(opacity 0.5)
		(translate (vector (* (flxrnd) 1) 5 (* (flxrnd) 1)))
		(scale (vector (* 10 (gh 4)) 0.1 (* 10 (gh 9))))
		(shinyness 5)
		(specular (vector 1 1 1))
		(colour (vector (* 5 (gh 4)) (* (gh 6) 5) (* 5 (gh 8))))
		(let ((ob (build_cube)))	
			(active_box ob)
			(kick ob (vector (*(gh 5)speed) (*(gh 7)speed) (*(gh 9)speed) ))
			(twist ob (vector (* (- (gh 13) 0.5) rotsp) 
							  (* (- (gh 14) 0.5) rotsp) 
							  (* (- (gh 15) 0.5) rotsp) )))
	(pop))

(ground_plane (vector 0 1 0) 0)
(set_max_physical 500)
(blur 0)

(define (run_loop)	
	 (spawn))
	;(if (> (gh 10) 0.2) (spawn)))

(line_width 5)
(clear)
(ground_plane (vector 0 1 0) 0)	
(engine_callback "(run_loop)")

(reset_camera)
(show_axis 0)
(clear_colour (vector 1 0.7 1))
