(define list '())

(define (sphere)
	(push)
	(opacity 0.05)
	(colour (vector 1 1 1))
	(specular (vector 0 0 0))
	(shinyness 100)
	(texture (load_texture "green.png"))
	(set! list (cons (build_plane) list))
	(apply (car list))
	;parent (car list))
	(pop))

(define (line n)
	(translate (vector 0 0 -0.01))
	(scale (vector 1.1 1.1 1.1))
	(sphere)
	(if (eq? 0 n)
		1
		(line (- n 1))))


(define (update l c s)
	(if (null? l)
		'()
		(begin 
			(grab (car l))
			;(emissive (vector (gh c) (gh (+ c 1)) (gh (+ c 2)) ))
			;(specular (vector (*(gh s)100) (*(gh s)100) (*(gh s)100)))
			;(identity)
			(rotate (vector 0 0 (*(- 0.5 (gh s))10)))
			;(scale (vector (gh s) (gh s) (gh s) ))
			(ungrab)
			(update (cdr l) (+ c 1) (+ s 1)))))

(show_axis 0)
(clear)
(line 10)
(blur 0.1)
(engine_callback "(update list 1 1)")
