(define list '())

(define (sphere)
	(push)
	(opacity 1)
	(colour (vector 1 1 1))
	(specular (vector 1 1 0))
	(shinyness 100)
	(texture (load_texture "green.png"))
	(set! list (cons (build_sphere 10 10) list))
	(apply (car list))
	;parent (car list))
	(pop))

(define (line n)
	(translate (vector 1 0 0))
	(sphere)
	(if (eq? 0 n)
		1
		(line (- n 1))))

(define (grid m n)
	(translate (vector 0 1 0))
	(push)
	(line n)
	(pop)
	(if (eq? 0 m)
		1
		(grid (- m 1) n)))

(define (update l c s)
	(if (null? l)
		'()
		(begin 
			(grab (car l))
			;(emissive (vector (gh c) (gh (+ c 1)) (gh (+ c 2)) ))
			(specular (vector (*(gh s)100) (*(gh s)100) (*(gh s)100)))
			;(identity)
			(rotate (vector (*(- 0.5 (gh s))10) (*(- 0.5 (gh s))10) (*(- 0.5 (gh s))10) ))
			;(scale (vector (gh s) (gh s) (gh s) ))
			(ungrab)
			(update (cdr l) (+ c 1) (+ s 1)))))

(show_axis 0)
(clear)
(grid 5 10)
(blur 1)
(display list)
(engine_callback "(update list 1 1)")
