(colour #(0.5 0.5 0.5))

(define (poly)
	(turtle-prim 1)
	(turtle-vert)
	(turtle-move 1)
	(turtle-turn #(0 90 0))
	(turtle-vert)
	(turtle-move 1)
	(turtle-turn #(0 90 0))
	(turtle-vert)
	(turtle-move 1)
	(turtle-vert)
	(turtle-turn #(0 180 0))
	(hint-none)
	(hint-wire)
	(turtle-build))

(define (shape n a)
	(poly)
	(display (/ 360 a))(newline)
	(turtle-turn (vector (/ 360 a) 0 0))
	(if (eq? n 0)
		1
		(shape (- n 1) a)))

;;(turtle-reset)
(backfacecull 0)
;(clear)
(clear-colour #(0.3 0.3 0.3))
(blur 0)
(show-axis 1)
(shape 10 10)