(colour #(0.5 0.5 0.5))

(define (poly)
	(turtle_prim 1)
	(turtle_vert)
	(turtle_move 1)
	(turtle_turn #(0 90 0))
	(turtle_vert)
	(turtle_move 1)
	(turtle_turn #(0 90 0))
	(turtle_vert)
	(turtle_move 1)
	(turtle_vert)
	(turtle_turn #(0 180 0))
	(hint_none)
	(hint_wire)
	(turtle_build))

(define (shape n a)
	(poly)
	(display (/ 360 a))(newline)
	(turtle_turn (vector (/ 360 a) 0 0))
	(if (eq? n 0)
		1
		(shape (- n 1) a)))

;;(turtle_reset)
(backfacecull 0)
;(clear)
(clear_colour #(0.3 0.3 0.3))
(blur 0)
(show_axis 1)
(shape 10 10)