(colour #(1 1 1))

(define (poly n)
	(turtle_prim 1)
	(turtle_vert)
	(turtle_move 1)
	(turtle_turn #(0 90 0))
	(turtle_vert)
	(turtle_move 1)
	(turtle_turn #(0 90 0))
	(turtle_vert)
	(turtle_move 1)
	(turtle_vert)
	(turtle_turn (vector (* (gh n) 2) 0 0))
	;(hint_none)
	;(hint_wire)
	(turtle_build))

(define (shape n a)
	(poly n)
	(turtle_turn (vector (/ 360 a) 0 0))
	(if (eq? n 0)
		1
		(shape (- n 1) a)))

(define (meta-shape nn)
	(rotate (vector 0 40 0)) 
	(shape 10 10)
	(if (eq? nn 0)
		1
		(meta-shape (- nn 1))))

;;(turtle_reset)
(backfacecull 0)
(engine_callback "(run)")

(define (run)
	(clear)
	(turtle_reset)
	(engine_callback "(run)")
	(push)
	(push)
	(meta-shape 10)
	(pop))

(clear_colour #(0.3 0.3 0.3))
(blur 0.1)
(show_axis 0)
(shape 10 10)