(define col 1)
(define sc 1)
(define rot 45)

(define (draw n)
	(push)
	(colour (vector (* col (gh (+ n 1))) 
					(* col (gh n) )
					(* col (gh (+ n 2)))))
	(scale (vector (* sc (gh (+ n 1))) 
					(* sc (gh n) )
					(* sc (gh (+ n 2)))))
	(scale (vector 2 0.2 0.2))
	(draw-cube)
	(pop)
	(if (eq? n 0)
		1
		(begin
			(push)
			(rotate (vector 0 (* 10 (gh n)) 0))
			(translate (vector 2 0 0))
			(draw (- n 1))
			(pop)

			(push)
			(rotate (vector 0 (* 40 (gh (+ n 4))) 0))
			(translate (vector 2 0 0))
			(draw (- n 1))
			(pop)

			(push)
			(rotate (vector 0 270 0))
			(translate (vector (* 10 (gh n)) 0 0))
			(draw (- n 1))
			(pop))))

(define (render)
	(push)
	(draw 5)
	(pop))

(clear)
(blur 0.01)
(clear-colour (vector 0 0 0))
(every-frame "(render)")

