env = Environment(CCFLAGS = '-pipe -Wall -O3 --fast-math -ggdb -Wno-unused  -fPIC')

PythonVersion = '2.3'
Prefix = '/usr/local/'
IncludePaths = [Prefix+"include/python"+PythonVersion,
				'/usr/local/include']
LibPaths = [Prefix+"lib/python"+PythonVersion+"/config",
			'usr/local/lib']

source = [
	'main.cpp'	
	]
	
libs = [
	'fluxus',
	'python'+PythonVersion,
	'pthread',
	'dl',
	'util'
	]
	
env.Program(source = source, CPPPATH=IncludePaths, LIBS=libs, LIBPATH=LibPaths, target = 'pyflux')
