###############################################################
# SConscript for fluxus material

import os	 
Import("env", "DataInstall")

Shaders    = ["shaders/simple.frag.glsl",
              "shaders/simple.vert.glsl",
              "shaders/blinn.frag.glsl",
              "shaders/blinn.vert.glsl",    
              "shaders/lambert.frag.glsl",
              "shaders/lambert.vert.glsl",
              "shaders/wrapped.frag.glsl",
              "shaders/wrapped.vert.glsl",
              "shaders/facingratio.frag.glsl",  
              "shaders/facingratio.vert.glsl", 
              "shaders/reflect.frag.glsl", 
              "shaders/reflect.vert.glsl", 
              "shaders/toon.frag.glsl",
              "shaders/toon.vert.glsl",
              "shaders/aniso.frag.glsl",
              "shaders/aniso.vert.glsl",
              "shaders/badprint.frag.glsl",
              "shaders/badprint.vert.glsl",
              "shaders/glossy.frag.glsl",
              "shaders/glossy.vert.glsl",
              "shaders/gooch.frag.glsl",
              "shaders/gooch.vert.glsl",
              "shaders/wood.frag.glsl",
              "shaders/wood.vert.glsl"]

Textures =   ["textures/gradient.png",
              "textures/green.png",
              "textures/refmap.png",  
              "textures/smoke.png",  
              "textures/test.png",
              "textures/track.png",
              "textures/transp.png",
              "textures/lights.png",
			  "textures/splat.png"]

TxtsInvaders = ["textures/invaders/barricade.png",
			  "textures/invaders/invader00.png",
			  "textures/invaders/invader01.png",
			  "textures/invaders/invader10.png",
			  "textures/invaders/invader11.png",
			  "textures/invaders/invader20.png",
			  "textures/invaders/invader21.png",
			  "textures/invaders/invaderxx.png",
			  "textures/invaders/missile00.png",
			  "textures/invaders/missile01.png",
			  "textures/invaders/missile02.png",
			  "textures/invaders/missile10.png",
			  "textures/invaders/missile11.png",
			  "textures/invaders/missile12.png",
			  "textures/invaders/missile20.png",
			  "textures/invaders/ship00.png",
			  "textures/invaders/ship01.png",
			  "textures/invaders/ship02.png"]

Meshes =      ["meshes/bot.obj", 
               "meshes/alien.obj",
               "meshes/rocket.obj",
               "meshes/mushroom.obj",
               "meshes/widget.obj",
               "meshes/octopus.obj"]

Samples =      ["samples/sample.wav"]

Fonts =      ["fonts/Bitstream-Vera-Sans-Mono.ttf"]

InstallShaders = DataInstall+"/material/shaders"
InstallTextures = DataInstall+"/material/textures"
InstallTxtsInvaders = DataInstall+"/material/textures/invaders"
InstallMeshes = DataInstall+"/material/meshes"
InstallFonts = DataInstall+"/material/fonts"
InstallSamples = DataInstall+"/material/samples"

env.Install(InstallShaders, Shaders)
env.Install(InstallTextures, Textures)
env.Install(InstallTxtsInvaders, TxtsInvaders)
env.Install(InstallMeshes, Meshes)
env.Install(InstallFonts, Fonts)
env.Install(InstallSamples, Samples)

