###############################################################
# SConscript for fluxus material

import os	 
Import("env", "DataInstall")

Shaders    = ["shaders/simple.frag.glsl",
              "shaders/simple.vert.glsl",
              "shaders/blinn.frag.glsl",
              "shaders/blinn.vert.glsl",    
              "shaders/lambert.frag.glsl",
              "shaders/lambert.vert.glsl",
			  "shaders/wrapped.frag.glsl",
              "shaders/wrapped.vert.glsl",
              "shaders/facingratio.frag.glsl",  
              "shaders/facingratio.vert.glsl", 
              "shaders/reflect.frag.glsl", 
              "shaders/reflect.vert.glsl", 
              "shaders/toon.frag.glsl",
              "shaders/toon.vert.glsl",
              "shaders/aniso.frag.glsl",
			  "shaders/aniso.vert.glsl",
              "shaders/badprint.frag.glsl",
			  "shaders/badprint.vert.glsl",
              "shaders/glossy.frag.glsl",
			  "shaders/glossy.vert.glsl",
              "shaders/gooch.frag.glsl",
			  "shaders/gooch.vert.glsl",
              "shaders/wood.frag.glsl",
			  "shaders/wood.vert.glsl"]

Textures =   ["textures/gradient.png",
              "textures/green.png",
              "textures/refmap.png",  
              "textures/smoke.png",  
              "textures/test.png",
              "textures/track.png",
              "textures/transp.png"]

Meshes =      ["meshes/bot.obj", 
			   "meshes/alien.obj",
			   "meshes/rocket.obj",
			   "meshes/mushroom.obj"]

Fonts =      ["fonts/Bitstream-Vera-Sans-Mono.ttf"]

InstallShaders = DataInstall+"/material/shaders"
InstallTextures = DataInstall+"/material/textures"
InstallMeshes = DataInstall+"/material/meshes"
InstallFonts = DataInstall+"/material/fonts"

env.Install(InstallShaders, Shaders)
env.Install(InstallTextures, Textures)
env.Install(InstallMeshes, Meshes)
env.Install(InstallFonts, Fonts)
