###############################################################
# SConscript for the Scheme PLT modules
#
# Should be ok for cross platform

import os	 
Import("env", "CollectsInstall")

Scripts    = ["scratchpad-boot.scm", 
			  "scratchpad.ss", 
			  "scratchpad-input.ss",
			  "scratchpad-camera.ss",
			  "fluxus-obj-import.ss" ]

Install        = CollectsInstall
InstallStartup = os.environ["HOME"]+"/.fluxus/"

env.Install(Install, Scripts)
env.Install(InstallStartup, ["startup.scm"])
env.Alias('install', InstallStartup)
