###############################################################
# SConscript for the Scheme PLT modules
#
# Should be ok for cross platform

import os	 
Import("env", "CollectsInstall")

Scripts    = ["scratchpad-boot.scm", 
			  "scratchpad.ss", 
			  "scratchpad-help.ss",
			  "scratchpad-input.ss",
			  "scratchpad-camera.ss",
			  "fluxus-obj-import.ss",
			  "fluxus-collada-import.ss",
			  "fluxus-building-blocks.ss",
			  "drflux.ss" ]

Install        = CollectsInstall

env.Install(Install, Scripts)
