###############################################################
# SConscript for the Scheme PLT modules
#
# Should be ok for cross platform

import os	 
Import("env", "CollectsInstall")

Scripts    = ["boot.scm", 
			  "fluxus.ss", 
			  "scratchpad.ss", 
			  "help.ss",
			  "input.ss",
			  "camera.ss",
			  "obj-import.ss",
			  "obj-export.ss",
			  "collada-import.ss",
			  "building-blocks.ss",
			  "drflux.ss",
			  "randomness.ss",
			  "frisbee.ss",
			  "fluxa.ss" ]

Install        = CollectsInstall

env.Install(Install, Scripts)
