###############################################################
# SConscript for fluxus-midi
#
# This is the main PLT module for the fluxus midi functions

Import("env", "BinaryModulesLocation", "MZDYN")

if env['PLATFORM'] == 'darwin':
	Target = "fluxus-midi_ss.dylib"
else:
	Target = "fluxus-midi_ss.so"

Install = BinaryModulesLocation

Source = ["src/FluxusMIDI.cpp",
		"src/MIDIListener.cpp",
		"src/RtMidi.cpp",
		MZDYN]

if env['PLATFORM'] == 'posix':
	Libs =  ['pthread', 'asound']
	Frameworks = []
	env.Append(CCFLAGS = ' -D__LINUX_ALSASEQ__')
elif env['PLATFORM'] == 'darwin':
	Libs = []
	env.Append(CCFLAGS = ' -D__MACOSX_CORE__')
	Frameworks = ['CoreMidi', 'CoreAudio', 'CoreFoundation', 'PLT_MrEd']

env.SharedLibrary(source = Source, 
				  target = Target,
				  LIBS = Libs,
				  FRAMEWORKS = Frameworks,
				  SHLIBPREFIX = "")
						 
env.Install(Install, Target)

